server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver #Todo 有啥区别
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.128.3.251:3306/atguigu_cloud_2020?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456

eureka:
  client:
    register-with-eureka: true          # 表示是否将自己注册进 Eureka Server
    fetch-registry: true                # 是否从 Eureka Server 抓取已有的注册信息。单节点无所谓，集群必须设置为 true 才能配合 ribbon 使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    prefer-ip-address: true #在eureka中显示ip:${spring.application.name}
    instance-id: ${spring.application.name}:${server.port} #设置在eureka中别名，如果不加，默认显示ip：

    lease-renewal-interval-in-seconds: 5      # 微服务向 Eureka 发送心跳信息的时间间隔，单位为秒（默认是30秒）
    lease-expiration-duration-in-seconds: 10   # Eureka 在收到最后一次心跳后等待的时间上限，超时将提出服务，单位为秒（默认是90秒）